-- AlterTable
ALTER TABLE "Object" ALTER COLUMN "createdDate" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Right" ALTER COLUMN "createdDate" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "RightObject" ALTER COLUMN "createYn" SET DEFAULT false,
ALTER COLUMN "deleteYn" SET DEFAULT false,
ALTER COLUMN "createdDate" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "RoleRight" ALTER COLUMN "createdDate" SET DEFAULT CURRENT_TIMESTAMP;
