
name: 'jewelry'
services:
  api:
    build: .
    restart: unless-stopped
    ports:
      - '3034:3000'
    environment:
      - DATABASE_URL=postgres://postgres:27102003@postgres:5432/jewelry

volumes:
  postgres_data:
  minio_data: 
