version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - NODE_EXTRA_CA_CERTS=/usr/local/share/ca-certificates/minio.crt
      - NODE_ENV=production
      - PORT=3000
      - DEV_DB_HOST=postgres
      - DEV_DB_PORT=5432
      - DEV_DB_USERNAME=postgres
      - DEV_DB_PASSWORD=27102003
      - DEV_DB_DATABASE=jewelry
      - DATABASE_URL=postgresql://postgres:27102003@postgres:5432/jewelry
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_USE_SSL=true
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=password123
      - MINIO_BUCKET=public
      - MINIO_HOST=minio
      - JWT_SECRET=94vFo1lmQQ
      - JWT_REFRESH_SECRET=94vFo1lmQQ
      - EXPIRE_AT=1d
      - MAIL_HOST=smtp.gmail.com
      - MAIL_USER=nguyenduy7003@gmail.com
      - MAIL_PASSWORD=tesf daab xvbr fyqo
      - MAIL_FROM=nguyenduy7003@gmail.com
      - CLOUDINARY_CLOUD_NAME=do2vkobzg
      - CLOUDINARY_API_KEY=384362255338848
      - CLOUDINARY_API_SECRET=0LBnBJ22MNuzhBO7h8PYyzoIv2I
      - VNP_TMNCODE=AUBE83HC
      - VNP_HASHSECRET=ROSW2WG139LSWVWXS7YJMA6KJMLF77TY
      - VNP_URL=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
      - VNP_RETURNURL=http://34.143.128.5/payment_return
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - postgres
      - minio

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=27102003
      - POSTGRES_DB=jewelry
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001" --address ":9000"
    volumes:
      - minio-data:/data
      - ./minio/certs:/root/.minio/certs
    ports:
      - "9000:9000"  # Cổng web API
      - "9001:9001"  # Cổng quản trị
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password123
      - MINIO_DOMAIN=minio.dclux.store  
      - MINIO_SERVER_URL=https://minio.dclux.store:9000
      - MINIO_CONSOLE_TLS=true  

  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
      environment:
        - discovery.type=single-node
        - xpack.security.enabled=false # Tắt bảo mật cho đơn giản (cân nhắc bật trong production)
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      ports:
        - "9200:9200"
        - "9300:9300"
      volumes:
        - esdata:/usr/share/elasticsearch/data

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt  # nơi chứa certbot certs
      - ./certbot/www:/var/www/certbot   # nơi certbot challenge lưu file
    depends_on:
      - app
      - minio
volumes:
  pgdata:
  minio-data:
  esdata: