import { MigrationInterface, QueryRunner } from "typeorm";

export class InitMigration1740729208048 implements MigrationInterface {
    name = 'InitMigration1740729208048'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "object_entity" ("id" SERIAL NOT NULL, "code" character varying(30), "name" character varying(30), "createdDate" TIMESTAMP, "createdBy" character varying(50), "updatedDate" TIMESTAMP, "updatedBy" character varying(50), "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_492d3c96261431a899e894a8088" UNIQUE ("code"), CONSTRAINT "PK_48c917693356ae868326dda8c47" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "right_object" ("id" SERIAL NOT NULL, "rightId" integer NOT NULL, "objectId" integer NOT NULL, "createYn" boolean NOT NULL DEFAULT true, "readYn" boolean NOT NULL DEFAULT true, "updateYn" boolean NOT NULL DEFAULT false, "deleteYn" boolean NOT NULL DEFAULT true, "executeYn" boolean NOT NULL DEFAULT true, "createdDate" TIMESTAMP, "createdBy" character varying(50), "updatedDate" TIMESTAMP, "updatedBy" character varying(50), "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_1970ffba17afc1773ce8a9ef48b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "right" ("id" SERIAL NOT NULL, "code" character varying(30), "name" character varying(30), "createdDate" TIMESTAMP, "createdBy" character varying(50), "updatedDate" TIMESTAMP, "updatedBy" character varying(50), "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_77e01b46d514d44ec33fd2d93d3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "role_right" ("id" SERIAL NOT NULL, "roleId" integer NOT NULL, "rightId" integer NOT NULL, "createdDate" TIMESTAMP, "createdBy" character varying(50), "updatedDate" TIMESTAMP, "updatedBy" character varying(50), "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_df0816e7f526f69342040a48469" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "role" ("id" SERIAL NOT NULL, "code" character varying NOT NULL DEFAULT 'USER', "name" character varying NOT NULL, "createdAt" TIMESTAMP DEFAULT now(), "updatedAt" TIMESTAMP, "isActive" boolean NOT NULL DEFAULT true, "createdBy" character varying(50), "updatedBy" character varying(50), CONSTRAINT "UQ_ee999bb389d7ac0fd967172c41f" UNIQUE ("code"), CONSTRAINT "PK_b36bcfe02fc8de3c57a8b2391c2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "comment" ("id" SERIAL NOT NULL, "parentId" integer NOT NULL, "content" text NOT NULL, "createAt" TIMESTAMP NOT NULL DEFAULT now(), "authorId" uuid NOT NULL, CONSTRAINT "PK_0b0e4bbc8415ec426f87f3a88e2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "comments_on_blogs" ("blogId" integer NOT NULL, "commentId" integer NOT NULL, CONSTRAINT "PK_f786b3d5e6b2707ad87bd439f8c" PRIMARY KEY ("blogId", "commentId"))`);
        await queryRunner.query(`CREATE TYPE "public"."blog_status_enum" AS ENUM('PENDING_APPROVAL', 'PENDING_DELETION', 'APPROVED', 'DELETED', 'ALL')`);
        await queryRunner.query(`CREATE TABLE "blog" ("id" SERIAL NOT NULL, "title" character varying NOT NULL, "content" text NOT NULL, "status" "public"."blog_status_enum" NOT NULL DEFAULT 'PENDING_APPROVAL', "createAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP, "authorId" uuid NOT NULL, CONSTRAINT "PK_85c6532ad065a448e9de7638571" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "profile" ("id" SERIAL NOT NULL, "firstName" character varying, "lastName" character varying, "phoneNumber" character varying, "isActive" boolean NOT NULL DEFAULT true, "createAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP, "userId" uuid NOT NULL, "socialMedia" character varying, CONSTRAINT "UQ_a24972ebd73b106250713dcddd9" UNIQUE ("userId"), CONSTRAINT "REL_a24972ebd73b106250713dcddd" UNIQUE ("userId"), CONSTRAINT "PK_3dd8bfc97e4a77c70971591bdcb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "keyToken" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "refreshTokenUsed" text NOT NULL DEFAULT '', "refreshToken" character varying NOT NULL, "accessToken" character varying NOT NULL, "user_id" uuid, CONSTRAINT "REL_82ec2cad0a6b52b1f115e22b77" UNIQUE ("user_id"), CONSTRAINT "PK_2f965b2a505823d42065c997118" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "password" character varying NOT NULL, "username" character varying, "roleId" integer NOT NULL, "isVerified" boolean NOT NULL DEFAULT false, "tokenOTP" character varying, CONSTRAINT "UQ_e12875dfb3b1d92d7d7c5377e22" UNIQUE ("email"), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "files" ("fileId" uuid NOT NULL DEFAULT uuid_generate_v4(), "bucketName" character varying NOT NULL, "fileName" character varying NOT NULL, "fileUrl" character varying NOT NULL, CONSTRAINT "PK_25150aaac483703a4ade8353fc3" PRIMARY KEY ("fileId"))`);
        await queryRunner.query(`ALTER TABLE "right_object" ADD CONSTRAINT "FK_823b3940be0dcf3d94f7af9ebaa" FOREIGN KEY ("rightId") REFERENCES "right"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "right_object" ADD CONSTRAINT "FK_cf3620793a485b2edbe27810552" FOREIGN KEY ("objectId") REFERENCES "object_entity"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_right" ADD CONSTRAINT "FK_e23a99abf5e82f31facf7efc1a4" FOREIGN KEY ("roleId") REFERENCES "role"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_right" ADD CONSTRAINT "FK_968ad19cacb669e55be732f2896" FOREIGN KEY ("rightId") REFERENCES "right"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comment" ADD CONSTRAINT "FK_276779da446413a0d79598d4fbd" FOREIGN KEY ("authorId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments_on_blogs" ADD CONSTRAINT "FK_65fe55d4dbe6ee641cd3fa4e5c7" FOREIGN KEY ("blogId") REFERENCES "blog"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments_on_blogs" ADD CONSTRAINT "FK_a8d1b2f5341ddb1627e7b47d9a1" FOREIGN KEY ("commentId") REFERENCES "comment"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "blog" ADD CONSTRAINT "FK_a001483d5ba65dad16557cd6ddb" FOREIGN KEY ("authorId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "profile" ADD CONSTRAINT "FK_a24972ebd73b106250713dcddd9" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "keyToken" ADD CONSTRAINT "FK_82ec2cad0a6b52b1f115e22b772" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_c28e52f758e7bbc53828db92194" FOREIGN KEY ("roleId") REFERENCES "role"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_c28e52f758e7bbc53828db92194"`);
        await queryRunner.query(`ALTER TABLE "keyToken" DROP CONSTRAINT "FK_82ec2cad0a6b52b1f115e22b772"`);
        await queryRunner.query(`ALTER TABLE "profile" DROP CONSTRAINT "FK_a24972ebd73b106250713dcddd9"`);
        await queryRunner.query(`ALTER TABLE "blog" DROP CONSTRAINT "FK_a001483d5ba65dad16557cd6ddb"`);
        await queryRunner.query(`ALTER TABLE "comments_on_blogs" DROP CONSTRAINT "FK_a8d1b2f5341ddb1627e7b47d9a1"`);
        await queryRunner.query(`ALTER TABLE "comments_on_blogs" DROP CONSTRAINT "FK_65fe55d4dbe6ee641cd3fa4e5c7"`);
        await queryRunner.query(`ALTER TABLE "comment" DROP CONSTRAINT "FK_276779da446413a0d79598d4fbd"`);
        await queryRunner.query(`ALTER TABLE "role_right" DROP CONSTRAINT "FK_968ad19cacb669e55be732f2896"`);
        await queryRunner.query(`ALTER TABLE "role_right" DROP CONSTRAINT "FK_e23a99abf5e82f31facf7efc1a4"`);
        await queryRunner.query(`ALTER TABLE "right_object" DROP CONSTRAINT "FK_cf3620793a485b2edbe27810552"`);
        await queryRunner.query(`ALTER TABLE "right_object" DROP CONSTRAINT "FK_823b3940be0dcf3d94f7af9ebaa"`);
        await queryRunner.query(`DROP TABLE "files"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TABLE "keyToken"`);
        await queryRunner.query(`DROP TABLE "profile"`);
        await queryRunner.query(`DROP TABLE "blog"`);
        await queryRunner.query(`DROP TYPE "public"."blog_status_enum"`);
        await queryRunner.query(`DROP TABLE "comments_on_blogs"`);
        await queryRunner.query(`DROP TABLE "comment"`);
        await queryRunner.query(`DROP TABLE "role"`);
        await queryRunner.query(`DROP TABLE "role_right"`);
        await queryRunner.query(`DROP TABLE "right"`);
        await queryRunner.query(`DROP TABLE "right_object"`);
        await queryRunner.query(`DROP TABLE "object_entity"`);
    }

}
