name: Deploy to GCP

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-docker@v3
        with:
          docker-version: '20.10.17'

      - name: Deploy to GCP Server
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # Tạo SSH key từ secrets
          echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key

          # Kết nối SSH và thực hiện deploy
          ssh -o StrictHostKeyChecking=no -i private_key $SERVER_USERNAME@$SERVER_IP << 'EOF'
            # Cài đặt Docker và Docker Compose nếu chưa có
            if ! command -v docker &> /dev/null; then
              sudo apt-get update
              sudo apt-get install -y docker.io docker-compose
              sudo systemctl start docker
              sudo systemctl enable docker
            fi

            # Di chuyển vào thư mục hoặc clone nếu chưa có
            if [ -d ~/NestJs-TypeORM ]; then
              cd ~/NestJs-TypeORM
              git reset --hard origin/main
              git pull origin main
            else
              git clone https://github.com/Bduyy2703/NestJs-TypeORM.git ~/NestJs-TypeORM
              cd ~/NestJs-TypeORM
            fi

            # Đảm bảo quyền truy cập
            sudo chown -R $USER:$USER .

            # Dừng và khởi động lại container
            docker-compose down || true  # Bỏ qua lỗi nếu không có container
            docker-compose up -d --build

            # Kiểm tra trạng thái container
            sleep 10  # Đợi container khởi động
            if [ $(docker ps -q | wc -l) -ge 4 ]; then
              echo "Deploy successful!"
            else
              echo "Deploy failed! Check logs."
              docker-compose logs
              exit 1
            fi
          EOF